//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_PA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLES_CARRITO
    {
        public int ID_DETALLE { get; set; }
        public int ID_CARRITO { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int CANTIDAD { get; set; }
    
        public virtual CARRITO CARRITO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
