//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_PA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS_ELECTRONICOS
    {
        public int ID_PRODUCTO_ELECTRONICO { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO { get; set; }
        public int STOCK { get; set; }
        public int ID_CATEGORIA { get; set; }
        public int ID_PROVEEDOR { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
