//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_PA
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESENAS
    {
        public int ID_RESENA { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int CALIFICACION { get; set; }
        public string COMENTARIO { get; set; }
        public System.DateTime FECHA_RESENA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
